FROM ubuntu:22.04

# Install dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    clang \
    llvm \
    libbpf-dev \
    linux-headers-generic \
    pkg-config \
    wget \
    git \
    && rm -rf /var/lib/apt/lists/*

# Install Go 1.21
RUN wget -q https://go.dev/dl/go1.21.0.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz && \
    rm go1.21.0.linux-amd64.tar.gz

ENV PATH=$PATH:/usr/local/go/bin
ENV GOPATH=/go
ENV PATH=$PATH:$GOPATH/bin

WORKDIR /app

# Set up BPF headers
RUN ln -sf /usr/include/x86_64-linux-gnu/asm /usr/include/asm && \
    ln -sf /usr/include/x86_64-linux-gnu/bits /usr/include/bits && \
    ln -sf /usr/include/x86_64-linux-gnu/sys /usr/include/sys && \
    ln -sf /usr/include/x86_64-linux-gnu/linux /usr/include/linux

# Install bpf2go tool
RUN go install github.com/cilium/ebpf/cmd/bpf2go@latest

# This container is meant for development
CMD ["/bin/bash"] 