// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceAccept4 *ebpf.ProgramSpec `ebpf:"trace_accept4"`
	TraceClose   *ebpf.ProgramSpec `ebpf:"trace_close"`
	TraceRead    *ebpf.ProgramSpec `ebpf:"trace_read"`
	TraceWrite   *ebpf.ProgramSpec `ebpf:"trace_write"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveFds    *ebpf.MapSpec `ebpf:"active_fds"`
	ConnState    *ebpf.MapSpec `ebpf:"conn_state"`
	EventStorage *ebpf.MapSpec `ebpf:"event_storage"`
	Events       *ebpf.MapSpec `ebpf:"events"`
	ProcessInfo  *ebpf.MapSpec `ebpf:"process_info"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveFds    *ebpf.Map `ebpf:"active_fds"`
	ConnState    *ebpf.Map `ebpf:"conn_state"`
	EventStorage *ebpf.Map `ebpf:"event_storage"`
	Events       *ebpf.Map `ebpf:"events"`
	ProcessInfo  *ebpf.Map `ebpf:"process_info"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveFds,
		m.ConnState,
		m.EventStorage,
		m.Events,
		m.ProcessInfo,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceAccept4 *ebpf.Program `ebpf:"trace_accept4"`
	TraceClose   *ebpf.Program `ebpf:"trace_close"`
	TraceRead    *ebpf.Program `ebpf:"trace_read"`
	TraceWrite   *ebpf.Program `ebpf:"trace_write"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceAccept4,
		p.TraceClose,
		p.TraceRead,
		p.TraceWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
