// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || amd64p32 || arm || arm64 || loong64 || mips64le || mips64p32le || mipsle || ppc64le || riscv64

package tracer

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

type bpfTraceEventRawSysEnter struct {
	Unused uint64
	Id     int64
	Args   [6]uint64
}

type bpfTraceEventRawSysExit struct {
	Unused uint64
	Id     int64
	Ret    int64
}

// loadBpf returns the embedded CollectionSpec for bpf.
func loadBpf() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_BpfBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load bpf: %w", err)
	}

	return spec, err
}

// loadBpfObjects loads bpf and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*bpfObjects
//	*bpfPrograms
//	*bpfMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadBpfObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// bpfSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfSpecs struct {
	bpfProgramSpecs
	bpfMapSpecs
}

// bpfSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfProgramSpecs struct {
	TraceAccept4     *ebpf.ProgramSpec `ebpf:"TraceAccept4"`
	TraceAccept4Exit *ebpf.ProgramSpec `ebpf:"TraceAccept4Exit"`
	TraceClose       *ebpf.ProgramSpec `ebpf:"TraceClose"`
	TraceConnect     *ebpf.ProgramSpec `ebpf:"TraceConnect"`
	TraceRead        *ebpf.ProgramSpec `ebpf:"TraceRead"`
	TraceReadRet     *ebpf.ProgramSpec `ebpf:"TraceReadRet"`
	TraceWrite       *ebpf.ProgramSpec `ebpf:"TraceWrite"`
}

// bpfMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type bpfMapSpecs struct {
	ActiveSockets *ebpf.MapSpec `ebpf:"active_sockets"`
	EventStorage  *ebpf.MapSpec `ebpf:"event_storage"`
	Events        *ebpf.MapSpec `ebpf:"events"`
	ReadArgsMap   *ebpf.MapSpec `ebpf:"read_args_map"`
	SocketInfo    *ebpf.MapSpec `ebpf:"socket_info"`
}

// bpfObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfObjects struct {
	bpfPrograms
	bpfMaps
}

func (o *bpfObjects) Close() error {
	return _BpfClose(
		&o.bpfPrograms,
		&o.bpfMaps,
	)
}

// bpfMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfMaps struct {
	ActiveSockets *ebpf.Map `ebpf:"active_sockets"`
	EventStorage  *ebpf.Map `ebpf:"event_storage"`
	Events        *ebpf.Map `ebpf:"events"`
	ReadArgsMap   *ebpf.Map `ebpf:"read_args_map"`
	SocketInfo    *ebpf.Map `ebpf:"socket_info"`
}

func (m *bpfMaps) Close() error {
	return _BpfClose(
		m.ActiveSockets,
		m.EventStorage,
		m.Events,
		m.ReadArgsMap,
		m.SocketInfo,
	)
}

// bpfPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadBpfObjects or ebpf.CollectionSpec.LoadAndAssign.
type bpfPrograms struct {
	TraceAccept4     *ebpf.Program `ebpf:"TraceAccept4"`
	TraceAccept4Exit *ebpf.Program `ebpf:"TraceAccept4Exit"`
	TraceClose       *ebpf.Program `ebpf:"TraceClose"`
	TraceConnect     *ebpf.Program `ebpf:"TraceConnect"`
	TraceRead        *ebpf.Program `ebpf:"TraceRead"`
	TraceReadRet     *ebpf.Program `ebpf:"TraceReadRet"`
	TraceWrite       *ebpf.Program `ebpf:"TraceWrite"`
}

func (p *bpfPrograms) Close() error {
	return _BpfClose(
		p.TraceAccept4,
		p.TraceAccept4Exit,
		p.TraceClose,
		p.TraceConnect,
		p.TraceRead,
		p.TraceReadRet,
		p.TraceWrite,
	)
}

func _BpfClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed bpf_bpfel.o
var _BpfBytes []byte
