version: "3.8"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - go-cache:/go
    ports:
      - "8080:8080"
    privileged: true
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined

volumes:
  go-cache:
