apiVersion: v1
kind: Pod
metadata:
  name: go-test-server
  namespace: monitoring
  labels:
    app: go-test-server
spec:
  containers:
    - name: server
      image: devshahriar/go-test-server:v1.0.0
      imagePullPolicy: Always
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
      env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: go-test-server
  namespace: monitoring
  labels:
    app: go-test-server
spec:
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: go-test-server
---
apiVersion: v1
kind: Pod
metadata:
  name: go-test-client
  namespace: monitoring
  labels:
    app: go-test-client
spec:
  containers:
    - name: client
      image: curlimages/curl:8.5.0
      imagePullPolicy: IfNotPresent
      command:
        - /bin/sh
        - -c
        - |
          while true; do
            # GET request
            echo "Making GET request..."
            curl -s -H "X-Custom-Header: uniquetest123" http://go-test-server:8080/get?param1=value1&param2=value2
            sleep 5

            # POST request with JSON body
            echo "Making POST request..."
            curl -s -X POST -H "Content-Type: application/json" -H "X-Custom-Header: uniquetest123" \
              -d '{"name":"test","value":"data"}' \
              http://go-test-server:8080/post
            sleep 5
          done
      resources:
        limits:
          cpu: 100m
          memory: 64Mi
        requests:
          cpu: 50m
          memory: 32Mi
