version: "3.8"

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - go-cache:/go
    command: sleep infinity
    cap_add:
      - SYS_PTRACE
      - NET_ADMIN
      - SYS_ADMIN
    security_opt:
      - seccomp=unconfined

volumes:
  go-cache:
