apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: abproxy-agent
  namespace: monitoring
  labels:
    app: abproxy-agent
spec:
  selector:
    matchLabels:
      app: abproxy-agent
  template:
    metadata:
      labels:
        app: abproxy-agent
    spec:
      hostPID: true
      hostNetwork: true
      containers:
        - name: abproxy-agent
          image: devshahriar/abproxy-agent:v1.0.2
          imagePullPolicy: Always
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_RESOURCE
                - SYS_PTRACE
                - NET_ADMIN
                - PERFMON
                - BPF
          volumeMounts:
            - name: sys
              mountPath: /sys
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: debugfs
              mountPath: /sys/kernel/debug
            - name: bpf
              mountPath: /sys/fs/bpf
          env:
            - name: DEBUG
              value: "true"
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: modules
          hostPath:
            path: /lib/modules
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: bpf
          hostPath:
            path: /sys/fs/bpf
            type: DirectoryOrCreate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: abproxy-agent
  namespace: monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abproxy-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abproxy-agent
subjects:
  - kind: ServiceAccount
    name: abproxy-agent
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: abproxy-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
