apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: abproxy-agent
  namespace: monitoring
  labels:
    app: abproxy-agent
spec:
  selector:
    matchLabels:
      app: abproxy-agent
  template:
    metadata:
      labels:
        app: abproxy-agent
    spec:
      hostPID: true
      hostNetwork: true
      initContainers:
        - name: bpf-mount
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              nsenter -t 1 -m -- /bin/sh -c '
              if ! mount | grep "type bpf"; then
                mount -t bpf bpf /sys/fs/bpf/
              fi
              mkdir -p /sys/fs/bpf/abproxy
              chmod 700 /sys/fs/bpf/abproxy
              # Set correct SELinux context if available
              if command -v chcon > /dev/null 2>&1; then
                chcon -R -t bpf_t /sys/fs/bpf/ || true
              fi
              # Ensure kernel allows unprivileged BPF
              if [ -f /proc/sys/kernel/unprivileged_bpf_disabled ]; then
                echo 0 > /proc/sys/kernel/unprivileged_bpf_disabled
              fi
              # Set resource limits
              if [ -f /proc/sys/net/core/bpf_jit_limit ]; then
                echo 1000000000 > /proc/sys/net/core/bpf_jit_limit
              fi
              '
          securityContext:
            privileged: true
          volumeMounts:
            - name: sys
              mountPath: /sys
      containers:
        - name: abproxy-agent
          image: devshahriar/abproxy-agent:v1.46.0
          imagePullPolicy: Always
          command:
            [
              "./abproxy-agent",
              "--storage=elasticsearch",
              "--es-url=http://elasticsearch-service.monitoring.svc.cluster.local:9200",
              "--es-prefix=abproxy",
            ]
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
                - SYS_RESOURCE
                - SYS_PTRACE
                - NET_ADMIN
                - PERFMON
                - BPF
                - IPC_LOCK # Added for memory locking
            runAsUser: 0 # Run as root
            allowPrivilegeEscalation: true
            seLinuxOptions:
              type: unconfined_t
          volumeMounts:
            - name: sys
              mountPath: /sys
            - name: modules
              mountPath: /lib/modules
              readOnly: true
            - name: debugfs
              mountPath: /sys/kernel/debug
            - name: cgroup
              mountPath: /sys/fs/cgroup
              readOnly: true
          env:
            - name: DEBUG
              value: "true"
            - name: LIBEBPF_IGNORE_VDSO_ERR
              value: "1"
            - name: BPF_FORCE_KERNEL_VERSION
              value: "0"
            - name: LOG_LEVEL
              value: "debug"
      volumes:
        - name: sys
          hostPath:
            path: /sys
        - name: modules
          hostPath:
            path: /lib/modules
        - name: debugfs
          hostPath:
            path: /sys/kernel/debug
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: abproxy-agent
  namespace: monitoring
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abproxy-agent
rules:
  - apiGroups: [""]
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: abproxy-agent
subjects:
  - kind: ServiceAccount
    name: abproxy-agent
    namespace: monitoring
roleRef:
  kind: ClusterRole
  name: abproxy-agent
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
